### ISSUE TITLE
PreLive Task-list

### ISSUE THREAD

**Issue by glmn** [glmn/sm-gleague#1]
# Tasks
- [x] Initialize database connection
- [x] Set match id based on command line
- [x] Store granted players steam ids
- [x] Check if player granted to access server (based on his steam id)
- [x] Set player nick name if different
- [x] Set player team
- [x] Change match state to warmup if first player connected
- [x] Change match state to knife if all players ready and warmup ended
- [x] Wait for winner's teamleader decision (stay or swap)
- [x] Change match state to live on 3
- [x] Make 3 round restarts
- [x] Change match state to live

**Comment by glmn** [comment]
**Complete!**
